### ISSUE TITLE
use of context in main func

### ISSUE THREAD

**Issue by yuens1002** [mattdamon108/go-graphql-api-boilerplate#12]
hi there, just a question about this `context.Bakground()` call in main.go

```
func main() {
	db, err := db.ConnectDB()
	if err != nil {
		panic(err)
	}

	defer db.Close()
        // what's this call for? doesnt seem to be used for anything
	context.Background()
```

doesnt seem to be doing anything. why is it there?

**Comment by mattdamon108** [comment]
Hi, I'm sorry for my lack of response a while. It's been a while since I finished this project and I'm little bit off from Go project and busy with other projects as well.

I recovered my memory when I implemented this `context.Context`. It was the purpose to use the context to make a context with data to use in my whole application, such as useID. When my go graphQL API gets a request with authorization header then uncapsulate it to get a userID inside JWT token. If it success, then it is added to context and flow all around in API application.

* validate the JWT and fluid it to context
https://github.com/mattdamon108/go-graphql-api-boilerplate/blob/8ac55961ea591cd109cb150cace01d7808f192f9/handler/auth.go#L18

* use it
https://github.com/mattdamon108/go-graphql-api-boilerplate/blob/8ac55961ea591cd109cb150cace01d7808f192f9/resolvers/change_password.go#L12
